"""add contest status

迁移 ID: d46665d9fa1b
父迁移: 
创建时间: 2025-12-31 18:54:55.897494

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd46665d9fa1b'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("dragon_contest",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dragon_contest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_ts', sa.Integer(), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('target', sa.JSON(), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dragon_contest')),
    info={'bind_key': 'dragon_contest'}
    )
    with op.batch_alter_table('dragon_contest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dragon_contest_start_ts'), ['start_ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_dragon_contest_status'), ['status'], unique=False)

    op.create_table('dragon_contest_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_limit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dragon_contest_config')),
    info={'bind_key': 'dragon_contest'}
    )
    op.create_table('dragon_contest_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('dragon_name', sa.String(length=32), nullable=False),
    sa.Column('eliminated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['dragon_contest.id'], name=op.f('fk_dragon_contest_player_contest_id_dragon_contest')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dragon_contest_player')),
    sa.UniqueConstraint('contest_id', 'user_id', name=op.f('uq_dragon_contest_player_contest_id')),
    info={'bind_key': 'dragon_contest'}
    )
    with op.batch_alter_table('dragon_contest_player', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dragon_contest_player_contest_id'), ['contest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dragon_contest_player_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dragon_contest_player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dragon_contest_player_user_id'))
        batch_op.drop_index(batch_op.f('ix_dragon_contest_player_contest_id'))

    op.drop_table('dragon_contest_player')
    op.drop_table('dragon_contest_config')
    with op.batch_alter_table('dragon_contest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dragon_contest_status'))
        batch_op.drop_index(batch_op.f('ix_dragon_contest_start_ts'))

    op.drop_table('dragon_contest')
    # ### end Alembic commands ###
